services:
   chromadb:
    container_name: mentora-chromadb
    image: chromadb/chroma:latest
    ports:
      - "8338:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - PERSIST_DIRECTORY=/chroma/chroma
      - CHROMA_SERVER_ALLOW_RESET=true
      - CHROMA_SERVER_CORS_ALLOW_ORIGINS=["*"] 
    volumes:
      - chroma-data:/chroma/chroma
    restart: always